services:
  nginx:
    build: ./nginx
    networks:
      - backend

  portainer:
    image: portainer/portainer-ce
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.18
    networks:
      - backend

  redis:
    image: redis:latest
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - backend

  employeemgmt.heartbeat:
    image: ghcr.io/sumter-utilities-inc/employeemgmt.heartbeat:latest
    networks:
      - backend

  employeemgmt.web:
    image: ghcr.io/sumter-utilities-inc/employeemgmt.web:latest
    networks:
      - backend
    extra_hosts:
      - "auth.sumterportal.com:172.17.0.1"
      - "identity.sumterportal.com:172.17.0.1"
    

  employeesmanagement.api:
    image: ghcr.io/sumter-utilities-inc/employeesmanagement.api:latest
    networks:
      - backend

  employeesmanagement.eventbus:
    image: ghcr.io/sumter-utilities-inc/employeesmanagement.eventbus:latest
    networks:
      - backend

  employeesmanagement.mfe:
    image: ghcr.io/sumter-utilities-inc/xxPRODENVxxemployeesmanagement.mfe:latest
    networks:
      - backend


  apprenticeshipprogram.heartbeat:
    image: ghcr.io/sumter-utilities-inc/apprenticeshipprogram.heartbeat:latest

  apprenticeshipprogram.web:
    image: ghcr.io/sumter-utilities-inc/apprenticeshipprogram.web:latest
    extra_hosts:
      - "auth.sumterportal.com:172.17.0.1"
      - "identity.sumterportal.com:172.17.0.1"

networks:
  backend:
    name: backend

volumes:
  portainer_data:
  elasticsearch-data:
  elasticsearch-productivity-data:
  elasticsearch-dukeenergyintegration-data:
  elasticsearch-employeesmanagement-data:
